### ISSUE TITLE
Is the pretrained model weight availabel now?

### ISSUE THREAD

**Issue by ValMystletainn** [jwohlwend/boltz#1]
awesome job! amzaing!!
But may I ask that will you release a pretrained weight and if it will, how long will it takes?

**Comment by jwohlwend** [comment]
The pretrained weights are already available! They download automatically when you launch the `boltz predict` command. Here's also a [direct link](https://www.dropbox.com/scl/fi/8qo9aryyttzp97z74dchn/boltz1.ckpt?rlkey=jvxl2jsn0kajnyfmesbj4lb89&st=dipi1sbw&dl=1)

**Comment by Vaibhavs10** [comment]
Hi @jwohlwend - Congrats on the release! I'm VB from the open source team at Hugging Face. Like @ValMystletainn I also had troubles finding the model weights, so I uploaded them over to the Hugging Face Hub over a community org: https://huggingface.co/boltz-community/boltz-1

I also opened a PR here: https://github.com/jwohlwend/boltz/pull/2 adding download support directly from the model repo too. Let me know if this works for you, I'm happy to add you as the admin or to transfer the weights to your namespace if you want! 🤗

**Comment by jwohlwend** [comment]
@Vaibhavs10 That's awesome, thanks for setting this up. Could you please make me the sole admin? My huggingface username is `jwohlwend`

**Comment by Vaibhavs10** [comment]
Done! You should’ve received an invite. I made you an admin and demoted my
role (feel free to remove me as well)

**Comment by jwohlwend** [comment]
Amazing, thanks a lot!!

**Comment by jwohlwend** [comment]
Weights are now on huggingface, and this is what is used by default in the repo! Thank you @Vaibhavs10 !!
