### ISSUE TITLE
plddt length mismatch

### ISSUE THREAD

**Issue by GriffinYoung** [jwohlwend/boltz#100]
I ran boltz1 on a protein with 501 residues and a ligand, so I was expecting a plddt vector of length 502. When I read the plddt_model_0.npz file, however, there are 528 entries. What are these extra entries? Also would it be possible to add the plddt scores as the b_factor in the output structure like alphafold does?

**Comment by gcorso** [comment]
Ligands are tokenized at atomic level, so there should be a pLDDT entry for every atom of the ligand

**Comment by vecos1990** [comment]
@gcorso How can one auto extract the ligand pLDDT?
