### ISSUE TITLE
Can constraints specify that atoms belong to the same chain?

### ISSUE THREAD

**Issue by bestz123** [jwohlwend/boltz#101]
constraints:
    - bond:
        atom1: [CHAIN_ID, RES_IDX, ATOM_NAME]
        atom2: [CHAIN_ID, RES_IDX, ATOM_NAME]

Can the CHAIN_ID here be the same chain?

**Comment by rcossio** [comment]
Yes, it can

**Comment by gcorso** [comment]
Closing this for issue for now, let us know if you run into any problem using this!
