### ISSUE TITLE
Guidelines for Extending CCD Library

### ISSUE THREAD

**Issue by rcossio** [jwohlwend/boltz#103]
Hi there! 
I’m working with the [CCD library](https://huggingface.co/boltz-community/boltz-1/resolve/main/ccd.pkl), and I was wondering if you could provide some guidelines or documentation on how this pickle file was originally generated. This would be very valuable for extending the library to custom residues.

I’ve encountered a problem: when I load the CCD library pickle and then immediately dump it again (even without making any modifications), the atom-level properties (e.g., `atom.GetProp("name")`) are lost in the newly created pickle file. The mapping from AminoAcid (string) → Molecule (RDKit) is preserved, but per-atom properties are not.

Below is a simple reproducible example:

```
import pickle
import sys

print('Python Version:', sys.version) # Python Version: 3.13.0 | packaged by conda-forge | (main, Oct  8 2024, 20:04:32) [GCC 13.3.0]

ccd_lib_file = '/path/to/downloaded/pickle/file/ccd.pkl'
ccd_lib_modified_file = '/path/to/newly/created/pickle/file/ccd_mod.pkl'

ccd_lib = pickle.load(open(ccd_lib_file, 'rb'))
print([atom.GetProp("name") for atom in ccd_lib["GLY"].GetAtoms()]) # ['N', 'CA', 'C', 'O', 'OXT', 'H', 'H2', 'HA2', 'HA3', 'HXT']
pickle.dump(ccd_lib, open(ccd_lib_modified_file, 'wb'))

# Sanity check
ccd_lib = pickle.load(open(ccd_lib_modified_file, 'rb'))
print([atom.GetProp("name") for atom in ccd_lib["GLY"].GetAtoms()]) # Key Error: 'name'
```

I also tried making a `deepcopy` before dumping, but the properties still vanish.

Questions:
- Could you provide any details on how the `ccd.pkl` was created?
- Is there a recommended approach to preserve these atom-level properties when re-pickling the data?

Thank you in advance for your help!

**Comment by benf549** [comment]
I believe you need to run this line after loading rdkit.

```
Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)
```

I wrote a notebook for adding to the CCD for general covalent modifications here: https://github.com/benf549/boltz-generalized-covalent-modification/blob/main/boltz_generalized_covalent_inference.ipynb and ran in to the same issue with loading and saving the cached ccd without this line.

**Comment by rcossio** [comment]
Thank you very much!
