### ISSUE TITLE
setup.py missing ?

### ISSUE THREAD

**Issue by tubiana** [jwohlwend/boltz#113]
Hi :-) 

First of all, thank you for your fantastic work on Botlz-1. Out of curiosity, we cannot install locally botlz throught `pip install -e .` because the file `steup.py`is missing. Would it be possible to add it in the github as well ?

Thank you and best regards,
Thibault.

**Comment by jwohlwend** [comment]
You do not need a setup.py when using pyproject.toml :) I ve been able to install locally myself. What error do you get? Maybe there’s a pip version mismatch or something?

**Comment by tubiana** [comment]
Thank you for your prompt response, I only see it now.. 
Well, I will close the issue because it's working now. I don't know what I did... The error was something like `no setup.py found`. 
I have created a new env, so maybe my pip with not uptodate, or mostlikely... I was on the wrong folder... 
Sorry for the disturbance, and thank you again for all the effort you put on BOLTZ 😊
