### ISSUE TITLE
Installation error on cluster

### ISSUE THREAD

**Issue by prathithbhargav** [jwohlwend/boltz#12]
when I try to install boltz on my cluster by `pip install boltz==0.0.0`, I get the following error: 

INFO: pip is looking at multiple versions of boltz to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement rdkit==2024.3.6 (from boltz) (from versions: 2022.3.3, 2022.3.4, 2022.3.5, 2022.9.1, 2022.9.2, 2022.9.3, 2022.9.4, 2022.9.5, 2023.3.1, 2023.3.2, 2023.3.3, 2023.9.1, 2023.9.2, 2023.9.3, 2023.9.4, 2023.9.5, 2023.9.6, 2024.3.1, 2024.3.2)
ERROR: No matching distribution found for rdkit==2024.3.6
I am using python 3.10.  Would it be better to git clone and install instead?

**Comment by jwohlwend** [comment]
I'm running some tests to check that our versions are consistent with the different python versions we allow, I'll report back!

**Comment by JoeYoLee** [comment]
### When I installed rdkit via pip, the following error occurred:
pip install rdkit==2024.3.6
ERROR: Could not find a version that satisfies the requirement rdkit==2024.3.6 (from versions: 2022.3.3, 2022.3.4, 2022.3.5, 2022.9.1, 2022.9.2, 2022.9.3, 2022.9.4, 2022.9.5, 2023.3.1, 2023.3.2, 2023.3.3, 2023.9.1, 2023.9.2, 2023.9.3, 2023.9.4, 2023.9.5, 2023.9.6, 2024.3.1, 2024.3.2)
ERROR: No matching distribution found for rdkit==2024.3.6

### When I install rdkit through conda, the following error occurs:
conda install -c rdkit rdkit

Specifications:

  - rdkit -> python[version='>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=3.10
The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - python=3.10 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - rdkit -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.17

**So, are there any recommended versions?**

**Comment by JLSteenwyk** [comment]
I, too, am getting a similar error when installing on a cluster using Python version 3.10.4. Specifically, I'm installing inside of a fresh virtual environment and the error is:

```
ERROR: Cannot install boltz==0.0.0 and boltz==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    boltz 0.1.0 depends on rdkit==2024.3.6
    boltz 0.0.0 depends on rdkit==2024.3.6
```

**Comment by bpfliegel-turbine** [comment]
3.9.20 worked great for me

**Comment by jlingford** [comment]
> I, too, am getting a similar error when installing on a cluster using Python version 3.10.4. Specifically, I'm installing inside of a fresh virtual environment and the error is:
> 
> ```
> ERROR: Cannot install boltz==0.0.0 and boltz==0.1.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     boltz 0.1.0 depends on rdkit==2024.3.6
>     boltz 0.0.0 depends on rdkit==2024.3.6
> ```

Same issue here

**Comment by jlingford** [comment]
Issue has resolved for me now:

```
git clone https://github.com/jwohlwend/boltz.git
cd boltz
conda create -n boltz_env python=3.12.7
conda activate boltz_env
pip install -e .
```

**Comment by JoeYoLee** [comment]
> I've made an attempt to solve this in the latest release. Could you please try to `pip uninstall boltz` and `pip install boltz==0.2.0` and let me know if that solves the issue for you?

Thanks, this works for me


```bash
conda create -n boltz020 python=3.12.7 -y
conda activate boltz020
pip install boltz==0.2.0
```

**Comment by prathithbhargav** [comment]
with python 3.10 I get this error  
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 ea4f11a2904e2a8dc4b1833cc1b5181cde564edd0d5cd33e3c168eff2d1863f1
             Got        8227a5015d850a2dd8e61c4e5038ee3c548a79f9e7140c34c54f2741d45f26f9
I replicated the instructions from 

> > I've made an attempt to solve this in the latest release. Could you please try to `pip uninstall boltz` and `pip install boltz==0.2.0` and let me know if that solves the issue for you?
> 
> Thanks, this works for me
> 
> ```shell
> conda create -n boltz020 python=3.12.7 -y
> conda activate boltz020
> pip install boltz==0.2.0
> ```

and this works perfectly fine. I guess it would be nice if you could add a line saying create a python 3.12 environment.
