### ISSUE TITLE
properly use Tensor cores

### ISSUE THREAD

**Issue by emacocucci** [jwohlwend/boltz#134]
Hi, 

Fantastic work! I can test and obtain the prediction of the protein proposed in the example. 
However, when I test the ligand example I get the following: 

Checking input data.
Running predictions for 1 structure
Processing input data.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.98it/s]
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3060') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Predicting DataLoader 0:   0%|                                                                                                                                | 0/1 [00:00<?, ?it/s]| WARNING: ran out of memory, skipping batch
Predicting DataLoader 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [05:15<00:00,  0.00it/s]Number of failed examples: 1
Predicting DataLoader 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [05:15<00:00,  0.00it/s]

It seems I do not have enough memory but the software suggests to adjust the precision of the computation. Where should I change it? I have a RTX3060 with 12Gb, would this make any difference? What is the maximum computation I can afford with my card?

Thank you for the help! Fantastic work!!!

Ema

**Comment by gcorso** [comment]
Hi Ema, trying to change the precision of the computation for memory and speed optimization is something we plan to investigate, but it not might as trivial as simply changing it at inference time. Unfortunately without these on a 12 GB GPU you will only be able to fit very small systems because the model itself takes up a large portion of that. If you have time to experiment and investigate we'd love to know what you find.

**Comment by emacocucci** [comment]
Thank you Gabriele for the quick answer, I am not sure I would be able to put my hands in the code. 
However the software is phenomenal!
Thank you for this!
E

**Comment by emacocucci** [comment]
Thanks again
