### ISSUE TITLE
PAE Output

### ISSUE THREAD

**Issue by KeaunAmani** [jwohlwend/boltz#3]
First off extremely impressive work and thank you very much for open sourcing this project under a truly open license!

Secondly, I was wondering where I could obtain output metrics such as pAE as well as whether or not this feature has been implemented.

Thanks.

**Comment by jwohlwend** [comment]
Hi! Yes, we are actively working on releasing the confidence model, at which point we will be able to provide these metrics. Should be very soon.

**Comment by KeaunAmani** [comment]
Awesome, very much looking forward to it!

**Comment by jwohlwend** [comment]
This has now been released in v0.3.0!

**Comment by KeaunAmani** [comment]
Thanks, I saw the news on LinkedIn!
