### ISSUE TITLE
Featurizer failed error

### ISSUE THREAD

**Issue by abhinavgupta0110** [jwohlwend/boltz#31]
I am getting the following error when trying to predict protein complexes. It only happens sometimes, especially when trying to sample a lot.

Featurizer failed on {file_name} with error index 454656 is out of bounds for axis 0 with size 454656. Skipping.

CUDA device: 'NVIDIA H100 80GB HBM3'

It would be great if someone could tell the specific reason behind this error (unless it is purely a OOM problem). 

Thanks,
Abhinav

**Comment by jwohlwend** [comment]
Deuplicate of #4 . We're actively looking into this, it's been hard for us to replicate the issue on our end.

**Comment by shataisheng** [comment]
I encountered the same issue when I ran it on the CPU platform, but after increasing the RAM size of the computer, the error disappeared.
My FASTA file contains three proteins, and each of them contains 120 amino acids (aa). The program requires at least 25GB of RAM, even though the size of the trained model is only 6.5GB.

**Comment by jwohlwend** [comment]
I believe this may be fixed now. Please try the new release: `pip install boltz -U`

**Comment by gcorso** [comment]
Closing this for now, feel free to reopen if you still encounter issues with the new release!
