### ISSUE TITLE
mmseqs2 server use and disclaimer

### ISSUE THREAD

**Issue by jadolfbr** [jwohlwend/boltz#32]
Can you put a warning somewhere that the automatic MSA generation uses a server?  This is a pretty big gotcha for a lot of groups with sensitive information and companies. 

Also, as an alternative, can you add the commands you used to generate the MSAs for command line use or have some additional documentation here?  I've seen some of it in the issues (and thank you for trying to keep up with them!), but I think having this explicitly spelled out and alternatives would be needed here. 

Thanks.

**Comment by jwohlwend** [comment]
Hmm this is a good point, maybe the MSA construction should be a separate command to avoid this type of surprise. I'll think about the best approach.

And sure, we use colabfold to create our MSA's for both training and inference. I'll make sure to add docs on that!

**Comment by jwohlwend** [comment]
Ok I've made it an opt-in feature!

**Comment by jadolfbr** [comment]
Great, thanks!  Definitely a surprise that is not a fun one.  This would be great.  We are also working on a cmd-line implantation and can send it when we have it.

**Comment by jwohlwend** [comment]
This is now the behavior in the v0.2.1 release.

**Comment by jadolfbr** [comment]
Thank you!
