### ISSUE TITLE
Auto-generated MSA when using an input folder

### ISSUE THREAD

**Issue by max-overath** [jwohlwend/boltz#35]
First off thank you for providing this model and making it so user-friendly! 

I encountered the following issue: 

When running in batch mode with an input folder that contains several fasta files of protein-protein interactions (two protein chains per fasta) it seems like the auto-generated MSAs for the first fasta are used for all follow-up predictions which leads to wrong results. I get expected structures when running the fastas individually.

Fasta example:

```
>A|protein
DVQLQASGGGSVQAGGSLRLSCAASGYTIGPYCMGWFRQAPGKEREGVAAINMGGGITYYADSVKGRFTISQDNAKNTVYLLMNSLEPEDTAIYYCAADSTIYASYYECGHGLSTGGYGYDSWGQGTQVTVSSGRYPYDVPDYGSGRA
>B|protein
KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL
```

**Comment by jwohlwend** [comment]
Thanks for flagging this. You can correct. I have fixed this in the latest v0.2.1 release!
