### ISSUE TITLE
MSA pairing

### ISSUE THREAD

**Issue by heol1** [jwohlwend/boltz#41]
I realized that the current release does not support taxonomy-based MSA pairing or custom paired MSA. Even although I used `run_mmseqs` with `--use_msa_server`, it seems like it does not use the paired sequence information by the MMseqs2 server as `taxonomy` is set to `-1` for all as taxonomy table is not given to `parse_a3m` in the `main` function.
I am wondering when it would become available to use the functionality. I found a related issue, https://github.com/jwohlwend/boltz/issues/5, but have not seen commits related to this yet. 

Thanks for releasing the work under the truly "open" source license!

**Comment by jwohlwend** [comment]
Hi! I'm working on that, should be ready soon

**Comment by heol1** [comment]
Thanks for the prompt response!
