### ISSUE TITLE
MSA search by MMSEQ server 

### ISSUE THREAD

**Issue by Han00127** [jwohlwend/boltz#42]
Hi, thanks for all great work.

I have a question about confidential issues when we use 'use_msa_server' flag for our confidential target protein?

**Comment by jadolfbr** [comment]
Yea, it’s a server.  It will send your sequence to an external computer to
run the MSA.   You probably do not want to use this option.

However, if it’s a target, there may be less importance. Ie - it’s not a
lead compound.  It’s like googling sortof.  You have probably googled your
target and looked  it up on uniprot, maybe even the PDB.  You probably want
to err on the side of caution, but ultimately, that’s a choice you will
need to make.

**Comment by jwohlwend** [comment]
I cannot speak to the confidentiality of the server since it's an outside service not maintained by us. It's up to the user to decide. You are welcome to create your own MSA's of course. Setting up colabfold locally is fairly straightforward, as are the databases used by AlphaFold

**Comment by jwohlwend** [comment]
There is now an option to set your own URL for the colabfold server if you host it locally. Closing for now!
