### ISSUE TITLE
Confidence analysis for the predicted structure

### ISSUE THREAD

**Issue by gweemish** [jwohlwend/boltz#45]
Hi, I have run a couple of predictions on my own laptop. I was wondering if there is a way to get confidence analysis for the predicted structure..

Thank you.

**Comment by jwohlwend** [comment]
Yes, we will be releasing our confidence model very soon

**Comment by gweemish** [comment]
Thank you so much. I look forward to it! =)

**Comment by ani11452** [comment]
Excited for this addition! Is there an ETA on when this might be released?

**Comment by gcorso** [comment]
We've added the confidence model!
