### ISSUE TITLE
Evaluation criteria

### ISSUE THREAD

**Issue by xiaoli1115** [jwohlwend/boltz#46]
Hi Jeremy,

Thank you so much for sharing the boltz1 with us!

Currently we are trying to predict some protein-ligand complex cases, we got the results and successfully downloaded it, but when we tried to find the Evaluation criteria/ scores, we got nothing. 

So how to evaluate our results?

Thank you so much!

**Comment by jwohlwend** [comment]
We will be releasing out confidence model very soon!

**Comment by jwohlwend** [comment]
Has now been released in v0.3.0!

**Comment by xiaoli1115** [comment]
Excited! May I ask a question that how to evaluate the score, like, is it very confident, confident or very low? or how to visualize it ? Thank you so much!

confidence_score0.8144504427909851
ptm0.6312305927276611
iptm0.5645926594734192
ligand_iptm0.4999026358127594
protein_iptm0.5855854749679565
complex_plddt0.876914918422699
complex_iplddt0.7071197628974915
complex_pde1.8762571811676025
complex_ipde11.478374481201172
