### ISSUE TITLE
Guideline for locally generating MSAs

### ISSUE THREAD

**Issue by sangyeon-hits** [jwohlwend/boltz#48]
Hello, I'd like to reproduce the model's performance while generating MSAs locally.

I've got `colabfold_search` and `mmseqs2` as the search tools, and `uniref30_2302` and `colabfold_envdb_202108` as DBs following the white paper.

But I don't know the exact commands and workflow for generating `.a3m` files the same way the authors did.

In particular, as I understand, I need to pair MSAs of different chains using taxonomy. But I'm not sure the current code includes such because I expect that there should be a file containing the taxonomy annotations, which I don't see:

> We then assign taxonomy labels to all UniRef sequences using the taxonomy annotation provided by UniProt.

#32 asked a similar question *in addition to* the confidentiality of the mmseqs server, but that part seems to have been missed out.

**Comment by sangyeon-hits** [comment]
Related:

1. https://github.com/jwohlwend/boltz/issues/4#issuecomment-2494067009
2. https://github.com/jwohlwend/boltz/issues/4#issuecomment-2494979165

**Comment by zongmingchua** [comment]
I would also like some additional clarity on this point to enable local generation of MSAs that match the server use, thank you!

**Comment by gcorso** [comment]
Hi @sangyeon-hits you should now be able to deploy locally a colabfold server (following colabfold instructions), specify that at inference time and reproduce our pipeline. Moreover, we have now published the input files for both training and testing datasets.

**Comment by sangyeon-hits** [comment]
> Hi @sangyeon-hits you should now be able to deploy locally a colabfold server (following colabfold instructions), specify that at inference time and reproduce our pipeline. Moreover, we have now published the input files for both training and testing datasets.

Thank you for the answer, @gcorso.

For clarity, I wondered whether I should care about MSA pairing for prediction. And the answer is I don't need to:

> Hi, you don’t need to worry about pairing when using the msa server, we pair for you directly on the colabfold server. It’s not exactly the same pairing we use for training, but should be close enough!

kindly answered by @jwohlwend in the Slack workspace.

The remaining problem is that when I use `colabfold_search` to generate MSAs locally, the resulting MSAs are slightly different from those generated by `colabfold_batch`, which uses the ColabFold server.
But I reckon this last problem should be addressed at the ColabFold repo — https://github.com/sokrypton/ColabFold/issues/665
