### ISSUE TITLE
how to do protein-protein interactions?

### ISSUE THREAD

**Issue by ricomnl** [jwohlwend/boltz#5]
hi, from the docs it's currently not clear how to run boltz for two interacting proteins? do you keep the AF2.3MM convention of `<protein1>:<protein2>` or does one pass them as two separate chains with individually calculated msas? if the latter, where does the MSA pairing happen?

**Comment by amelie-iska** [comment]
It explains how to set up the YAML or the FASTA [here](https://github.com/jwohlwend/boltz/blob/main/docs/prediction.md). You just need a new entry for each unique protein.

**Comment by jwohlwend** [comment]
@amelie-iska is correct! Regarding pairing, I'll be adding a feature for user-defined pairing today or tomorrow, alongside other MSA related updates. For user-defined MSAs without any pairing key (which is what the current code allows but not for long), we default to random pairing. I'll add more documentation on this.
