### ISSUE TITLE
Ions? 

### ISSUE THREAD

**Issue by amelie-iska** [jwohlwend/boltz#52]
Will there be any attempt at modeling ions...or water?

**Comment by sangyeon-hits** [comment]
I haven't tried, but I expect that giving ions as SMILES in `ligand` part in the input might work?

**Comment by gcorso** [comment]
Ions can be added to the input both as smile or CCD specifications. At training time we included many ions as long as they were not market as a crystallization artifact.

The model was never trained on any water molecules nor we tried it at inference time, but once again you should be able to potentially add them to the input and see what happens (we don't have plans to include them in the training for now).
