### ISSUE TITLE
pip install boltz in python=3.10 does not work

### ISSUE THREAD

**Issue by totucuong** [jwohlwend/boltz#55]
Hi team,

I tried to install boltz in a conda env with python=3.10. I used the default command 'pip install boltz' and got the following error

`Requirement already satisfied: pip in ./miniconda3/envs/boltz/lib/python3.10/site-packages (24.2)
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install`

The command works if python=3.9. But according to the https://pypi.org/project/boltz/ python=3.10 should work also.

**Comment by sangyeon-hits** [comment]
How about directly installing the Git code? Such as:

```bash
conda create -n boltz_env python=3.10 pip
conda activate boltz_env
git clone https://github.com/jwohlwend/boltz.git
cd bolts
pip install .
# or for the editable mode:
pip install -e .
```

**Comment by gcorso** [comment]
You could also try to install with python 3.12 (as recommended in #12)

**Comment by totucuong** [comment]
Thanks @gcorso @sangyeon-hits
