### ISSUE TITLE
How to prepare .a3m for my own protein?

### ISSUE THREAD

**Issue by RuikangSun** [jwohlwend/boltz#6]
Hi! I found blotz helpful and successfully ran [samples](https://github.com/jwohlwend/boltz/tree/main/examples) in my own computer (with CPU mode). However, when I am preparing my own prediction, I'm not sure how .a3m MSA file (in [this document](https://github.com/jwohlwend/boltz/blob/main/docs/prediction.md)) is prepared. So any suggestion on how to prepare .a3m for my own protein? Thanks!

**Comment by ebettler** [comment]
I used (with success) https://toolkit.tuebingen.mpg.de/ web site (you can save in .a3m format in query MSA output page)
You could used also DeepMSA2: https://zhanggroup.org/DeepMSA
The last is longer but better

**Comment by jadolfbr** [comment]
Also have the same question.  The MSA, selection, etc. can greatly change results as well.  What was the method benchmarked with?  Can you add cmd-line example of this?  Thanks.

**Comment by alburse** [comment]
Here is the information from their technical report. 
"We construct MSAs for the full PDB data using the colabfold search tool [Mirdita et al., 2022] (which leverages MMseqs2 [Steinegger and S¨oding, 2017]), using default parameters (versions: uniref30 2302, colabfold envdb 202108)."

**Comment by amelie-iska** [comment]
MMseqs2 now has a GPU accelerated version "MMseqs2-GPU" as of Nov. 16 2024, which makes it much, much faster (thanks NVIDIA!). I think in general this is a good way to get MSAs.

**Comment by RuikangSun** [comment]
> I used (with success) https://toolkit.tuebingen.mpg.de/ web site (you can save in .a3m format in query MSA output page) You could used also DeepMSA2: https://zhanggroup.org/DeepMSA The last is longer but better

Thank you! I successfully run my own protein with https://toolkit.tuebingen.mpg.de/tools/patsearch
