### ISSUE TITLE
issues at runtime - --use_msa_server

### ISSUE THREAD

**Issue by YogBN** [jwohlwend/boltz#60]
Dear Jeremy,
First of all please accept my gratitude for your fine work. In terms of the issue, I went ahead and installed Boltz-1 in a fresh virtual environment  with conda. I then tried to model an multimer with RNA with a test.yaml but when I attempted to predict the structure of the multimer, the runtime failed saying "**Error: No such option--use_msa_server**".  In the yaml file, I have commented out the msa lines for both protein and RNA, since I want the MSA from MMSeqs2 web server.

Here is the command I used:

Boltz predict --devices 1 --recycling_steps 10 --diffussion_samples 10 --cache "path to cache directory" --out_dir "path to output directory" --accelerator gpu --use_msa_server True --msa_server_url https://api.colabfold.com --msa_pairing_strategy greedy

This results in the aforementioned error. The yaml file is as follows:

version: 1
sequences:
  - protein:
      id: [A,B,C,D,E,F,G,H]
      sequence: GDTPSNPLRPIADDTIDHASHTPGSVSSAFILEAMVNVISGPKVLMKQIPIWLPLGVADQKTYSFDSTTAAIMLASYTITHFGKATNPLVRVNRLGPGIPDHPLRLLRIGNQAFLQEFVLPPVQLPQYFTFDLTALKLITQPLPAATWTDDTPTGSN
#      msa:
  - rna:
      id: [I,J,K,L,M,N,O,P]
      sequence:UACAUUCCCAGCCUUUGUAGUGUUUUCGCCAAGCA
#      msa: 

Can you please provide me with some guidance why this standard use case is failing?

I look forward to hearing from you.

With warm regards,
Yogi

**Comment by sangyeon-hits** [comment]
Are you using the most recent commit of the Boltz code? The error looks trivial that the option is not considered valid.
And also, the option `--use_msa_server` is a flag, meaning that you only have to command like

```bash
boltz predict [args ...] --use_msa_server [other_options ...]
```

not like `--use_msa_server True`.

**Comment by zhuowenzhao** [comment]
However, git pull the latest commit and build from there works!

**Comment by YogBN** [comment]
Hi all,
Thanks for your assistance in this regard. I was able to move forward with my modeling but now run into "out of memory" issue as discussed by others in the issues forum.

Yogi
