### ISSUE TITLE
Retraining Boltz

### ISSUE THREAD

**Issue by jozhang97** [jwohlwend/boltz#61]
Hi team,

Thank you for the fantastic work! I'm excited to explore and build on top of this project.

I have a few questions about the training process:

- How many A100 GPUs were used for the final training run?
- How long did the final training run take (in wall-clock time)?

I couldn't find these details in the technical report, so I apologize if I missed them.

Additionally, do you have an estimate for when the training data will be fully uploaded to shareable storage and dataset installation instructions ready?

Thanks again for your efforts, and I appreciate any insights you can provide!

**Comment by gcorso** [comment]
Hi, it is a bit hard to accurately estimate the total wall-clock time as there were some server interruptions along the way. However, an estimate for the total training of both the structure prediction and confidence model is about 3 weeks on 128 A100 GPUs.

By next week we should have all the training data and instructions released!

**Comment by jozhang97** [comment]
Thank you for the timely response!
