### ISSUE TITLE
template structure as the input?

### ISSUE THREAD

**Issue by aravinda1879** [jwohlwend/boltz#63]
I wonder if there is any possibility to use template structures to guide PPI in cases we have information?

**Comment by gcorso** [comment]
Hi @aravinda1879, 

At the moment we do not support input structural templates (although we might add them in future iterations of the model).

On another note, we will soon add the support for specifying pocket/contact information, which can be very useful for the model predicting PPI interactions (when known, of course).

**Comment by ijpulidos** [comment]
I noticed that this issue is marked as completed, but as far as I can tell, support for input structural templates doesn’t appear to be implemented yet (unless I missed something). Could you clarify the status or provide an update?

Thank you for your help! (CC @sukritsingh )

**Comment by johnnytam100** [comment]
Same need here for template input.
