### ISSUE TITLE
different models were generated with the same input files

### ISSUE THREAD

**Issue by cryingmyth** [jwohlwend/boltz#64]
I really appreciate your hard work and dedication in creating this project.
In my case, several different models were generated separately when I used the same antibody-antigen sequence. So, how should I rank these models? Which one is more reliable?

**Comment by gcorso** [comment]
Hi @cryingmyth,

We just released, as part of version 0.3.0 a confidence model. This adds confidence metrics for the predictions. The model will already sort predictions based on the confidence_score but you can also try to directly use the specific inter-chain ipTM relevant for your antibody-antigen interaction.

I hope this helps!
