### ISSUE TITLE
complex_plddt missing

### ISSUE THREAD

**Issue by hmms117** [jwohlwend/boltz#67]
Hi,

Thank you for this excellent tool - and for making it open source 👍 I'm also impressed by how quickly features like pLDDT and chunking have been added—they're very useful additions.

Before the confidence scores, Boltz ran without many issues. Getting this error now across a few examples, including the test ligand.yaml example. 

```
  File "boltz/src/boltz/model/model.py", line 1130, in predict_step
    4 * out["complex_plddt"] + out["iptm"]
KeyError: 'complex_plddt'
```

Looking forward to testing chunking and exploring the confidence scores.

**Comment by gcorso** [comment]
Hi @hmms117, unfortunately, I am not able to replicate this issue (for me the confidence model runs as expected).
Could you try to change the cache folder or reinstall the repo in a new location/environment?

**Comment by hmms117** [comment]
Thanks @gcorso. Good to know its just me; I will try to do a clean install - and try another type of GPU. Odd the old versions work just fine.

Truly an awesome effort - initial results (with 0.1.0-0.2.0) look excellent! 👍

**Comment by hmms117** [comment]
Update: 0.3.0 has new weights. Cleared cache and all worked 👍

**Comment by smilenaderi** [comment]
@hmms117  how did you manage to solve it?
