### ISSUE TITLE
Truncated final protein chains

### ISSUE THREAD

**Issue by fregat17** [jwohlwend/boltz#70]
Hi team, thank you for your impressive work.

Unfortunately, I encountered a problem when generating homooligomeric complexes. The monomer length is 641 amino acids, but when I add more of the same chains, the final structure has only 219 amino acids per chain, and there are UNK residues after each chain (One UNK after each 219AA chain). This behavior is observed in di-, tri-, and tetramer complexes when viewed in PyMOL.

I'm using version 0.3.0, with an input .yaml file containing a list of chains [A, B, C, D] in the same protein entity and a 1xV100 GPU, if that matters.

**Comment by jwohlwend** [comment]
Hi, could you share your input YAML?

**Comment by fregat17** [comment]
Sorry for disturbing, actually my mistake
