### ISSUE TITLE
Job failure during batch processing of ligands

### ISSUE THREAD

**Issue by amrelaraby1** [jwohlwend/boltz#74]
When I submit a job with multiple FASTA files, each for a different ligand, the job fails when it is unable to generate the 3D structure of one of the input ligand SMILES. I wonder if there is a workaround to bypass the failed ligand(s) and continue with the rest. I am working on a scale of ~2000 ligands.

**Comment by gcorso** [comment]
Hi @amrelaraby1, thank you for the suggestion! I modified the code so that failed predictions within a batch are skipped 'graciously'. The update will be effective in the package version 0.4.1. Let me know if you run into any more issues!

**Comment by amrelaraby1** [comment]
Hi Gabriel,
Great! Thank you for adressing this. Can't wait for the update!

Amr

**Comment by gcorso** [comment]
Great! Closing this for now, please reopen if you still run into issues!
