### ISSUE TITLE
Finetuning Boltz with no MSA. 

### ISSUE THREAD

**Issue by AlexanderMath** [jwohlwend/boltz#75]
Any interest in PR / model weights finetuned to improve single-sequence performance? (e.g. using ESM activations as done in CHAI).

Asking after trying Crambin ([1EJG](https://www.rcsb.org/structure/1ejg)), saw 0.4 RMSD increase to 8-10 RMSD - curious if other see the same, scared I'm just doing something wrong.

**Comment by wckdouglas** [comment]
> Also, curious if anyone finetuned ESM to minimize |ESM(seq).MSA_head - MSA(seq)| - very hacky way to circumvent MSA pipeline engineering pain.

maybe not quite `minimize |ESM(seq).MSA_head - MSA(seq)|` but [vcmsa](https://pmc.ncbi.nlm.nih.gov/articles/PMC10538487/pdf/1145.pdf) uses prot-t5 embeddings to infer msa

**Comment by gcorso** [comment]
Hi, yes we do not expect good results without MSA as the model was specifically trained without ever dropping the input MSA. We currently do not have plans to integrate the ESM model, however, if there are particular use cases for which we hear people from the community requiring such inference mode we will consider adding it!

**Comment by gcorso** [comment]
Closing this issue for now, please reopen if anyone has any comment or request on this!
