### ISSUE TITLE
How to increase solution diversity?

### ISSUE THREAD

**Issue by varunmc92** [jwohlwend/boltz#85]
Thank you making this tool open source. I am currently using it to predict protein-protein complex structures. For a particular pair of protein sequences and diffusion samples=25, I am getting 25 models that are very similar to each other. I already know roughly where the binding interface is and models made in the 25 solutions do not have the correct binding interface. Will changing the sampling_steps and/or recycling_steps be helpful?

**Comment by gcorso** [comment]
i've exposed the step_scale parameter. By setting it lower (probably I would stay between 1.5 and 1) you can increase the diversity of the samples.

**Comment by varunmc92** [comment]
Thank you so much
