### ISSUE TITLE
About generating protein sequences embeddings with the model

### ISSUE THREAD

**Issue by christopher-irw** [jwohlwend/boltz#87]
Hi there,  

Thank you for your excellent work on this project. I’m wondering if your model can be used specifically for generating embeddings of protein sequences. For instance, given a protein sequence as input, is there a function available that outputs its embedding, which can then be used for downstream tasks?  

If this is possible, could you provide an example script or point to best practices for generating these embeddings effectively?  

Thank you!

**Comment by gcorso** [comment]
Hi @christopher-irw, not without doing a bit of modification to the code. However, you should be able to relatively easily use the single and pair representation coming out of the Pairformer (these are also the features fed to the confidence model): you can do this outputting s and z here https://github.com/jwohlwend/boltz/blob/c59aa53815c02f0028c812732a174b8422df6fa6/src/boltz/model/model.py#L318
