### ISSUE TITLE
Boltz not a package wut?

### ISSUE THREAD

**Issue by greenrace666** [jwohlwend/boltz#88]
I tried out everything I could think of ..... Pretty sure I definitely did pip install boltz

Traceback (most recent call last):
  File "/usr/local/bin/boltz", line 5, in <module>
    from boltz.main import cli
ModuleNotFoundError: No module named 'boltz.main'; 'boltz' is not a package

wat is even tis?

**Comment by jwohlwend** [comment]
Have not seen this one before. Can you try to reinstall in a fresh environment?

**Comment by greenrace666** [comment]
Got it .. boltz was not installed properly due to my broken python , fixed ✌️
