### ISSUE TITLE
Has the use of your model on this website been authorized by you：https://neurosnap.ai/service/Boltz-1%20(AlphaFold3)

### ISSUE THREAD

**Issue by nancywings** [jwohlwend/boltz#9]
Thank you for your excellent work！Do you have a web server available? Has the use of your model on this website ("https://neurosnap.ai/service/Boltz-1%20(AlphaFold3)")been authorized by you?   Is its functionality complete? Thank you very much!

**Comment by jwohlwend** [comment]
We are working on releasing a webserver. We are not involved with the link you sent!

**Comment by nancywings** [comment]
> We are working on releasing a webserver. We are not involved with the link you sent!
Thank you very much! When is your webserver expected to go live？

**Comment by nancywings** [comment]
Thank you very much! When is your webserver expected to go live？

**Comment by jwohlwend** [comment]
Really hard to say at this time, but we are working hard :)

**Comment by nancywings** [comment]
OK，Thanks again!
