### ISSUE TITLE
Quantization Option for Memory Issue and Inference Speed? 

### ISSUE THREAD

**Issue by amelie-iska** [jwohlwend/boltz#95]
Hi all, 
I'm still loving Boltz-1, despite having a bit of trouble on hemichannels and gap junctions...I was just thinking...it may be pretty quick and easy to offer a couple of quantized versions, maybe even one using Tim Dettmers' `nf4` data type [introduced in the QLoRA paper](https://arxiv.org/abs/2305.14314)? The "[Normal Float 4](https://github.com/bitsandbytes-foundation/bitsandbytes/issues/543)" data type is information theoretically optimal, so would be a really good option to offer, but I can also see less intense quantization being useful as well. Thoughts? Probably would be easier and quicker than sharding (which someone totally still needs to do).

**Comment by jwohlwend** [comment]
The thing with quantization is that it’s not a trivial thing to get working, it needs to be done in a way that conserves performance and this architecture is quite sensitive to precision. Something to think about in the future though! If someone wishes to try it and can demonstrate no loss in accuracy I’d be happy to dig in more but I m a bit skeptical

**Comment by amelie-iska** [comment]
Very good point...we are not generating images or poems after all. Loss in accuracy would be pretty devastating for this sort of thing. I'll ponder a bit more, but I agree, probably it would be too brutal on the model.

**Comment by amelie-iska** [comment]
Hmmm, any thoughts on the quantization of the structure tokens in ESM-3 and what that might imply? Obviously if you have to scale to 98B to make up for it...maybe not the best idea, but also, maybe the necessity of that many params is due to other things and not the quantization.

**Comment by jwohlwend** [comment]
This is quite a different discussion. Quantizing tokens is not the same as quantizing the weights of the model. If the goal is speed, I'm not sure this is very relevant.

**Comment by amelie-iska** [comment]
Yeah...I was not thinking through that one carefully enough. Quantizing embedding vectors is indeed a completely different problem from quantizing tokens. Sorry for the red herring.

**Comment by jwohlwend** [comment]
No problem. Always happy to discuss! Closing this for now.
