### ISSUE TITLE
Parallel GPU use

### ISSUE THREAD

**Issue by Jay-Beeb** [jwohlwend/boltz#97]
Hi!
Thanks for sharing this powerful tool!
I'm trying to predict complexes with multiple sequences and run out of memory fast. I noticed that only one of 4 GPUs is used during the prediction. It has 94GB of RAM and I'm able to predict complexes with 4 proteins (2000AA total) but not more. Is this normal memory usage and is there a way to use more GPUS in parallel? I tried --devices, but it seems to only spread predictions for different entities to other gpus.
Thanks in advance!

Jay

**Comment by jwohlwend** [comment]
We do not support sharding across GPU's at this time but you should be able to fold 2000 AA's with an 80G GPU (maybe even 48G)

**Comment by dhiraj82** [comment]
On the same line, although we can not parallelize boltz, but while prediction multiple binding/structure, can we run multiple instances of  boltz in same folder or use GNU parallel or do we have to split the list of input fasta sequences and provide each list to a different instance of boltz?

Thanks
Dhiraj
